### ISSUE TITLE
Add a script for testing push notifications

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#10]
Between [pem](https://github.com/fastlane/fastlane/tree/master/pem) and [houston](https://github.com/nomad/houston), we should be able to write a script (or lane for fastlane) to send test notifications on the sandbox APNS queue.

I'm picturing this as a starting point that can be adjusted for each project to match the expected payload from real push notifications. Since we're working our way toward a shared fastfile (see #9), it probably makes sense to do this in one or more scripts, rather than having project-specific lanes.

**Comment by bryanluby** [comment]
Closing this as we use other 3rd party tools for testing push.
