### ISSUE TITLE
Include template details in the project README

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#12]
The project template drops a mostly-empty `README.md` in new projects. This would be a good place to put information about the template, and potentially a new-project checklist—basically, what's already in the README here in this repo. That way, when you create a new project from the template, you just work your way down the checklist in the README that's in the project and remove todo items as they're completed.

**Comment by bryanluby** [comment]
Closing this as we have different upcoming plans for a templated README that maybe included here.
