### ISSUE TITLE
Change delivery of xUnique

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#13]
We've got [a fork of xUnique](https://github.com/vokal/xUnique) that was created so we could wrap the tool in a CocoaPod, to make it easier to bundle with new projects. This has since diverged from the actual projects, with 14 different commits on each side.

Ellen had submitted a pull request to add that functionality upstream (https://github.com/truebit/xUnique/pull/27), but the [maintainer isn't interested in merging it](https://github.com/truebit/xUnique/pull/27#issuecomment-243341247). We shouldn't be maintaining a fork of this tool just so we can include it as a pod. It didn't really make sense as a pod anyway: we only packaged it up that way to make it easy for other developers to pick up the project.

Let's find another way to include it using the appropriate tool for that job. xUnique can be installed on one's system using `pip install`, but that adds one more tool that developers need to have installed before they can work on the project. I think it's a better idea to include the script in the project repo (just like we're doing now, when it comes in a CocoaPod) to simplify things. That way, any developer that joins the project already has the script and doesn't need to run any additional setup.

This could be part of a new project setup script, if we add it in #7.

Alternatively, we could look for a comparable implementation in Ruby, and include it in the Gemfile.

**Comment by bryanluby** [comment]
Closing as we no longer use xUnique.
