### ISSUE TITLE
Consider adding handling for a QA server environment

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#2]
Both the Swift and Objective-C templates include some handling to choose the staging or production server environment. For some projects, we've also had a QA or UAT server that's used between staging and production.

We should consider adding handling for this to the project template. It can't hurt to have it in there, so maybe the next time we do this on a project, we can go through and update the template with the same changes.

**Comment by kevnm67** [comment]
If you decide to use dotenv ([mentioned here](https://github.com/vokal/Xcode-Template/issues/9#issuecomment-416201341)) one option is leveraging .env.staging, .env.qa, .env.development, etc.  Example: ```bundle exec fastlane build_qa --env qa```

**Comment by bryanluby** [comment]
Going to leave as-is with the standard staging + prod. Can always add additional environments depending on the project.
