### ISSUE TITLE
Consider including a starter for a debug menu

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#28]
See this blog post: https://blog.curtisherbert.com/cheat-codes/

It could be handy to have a starter in place for:

- A debug URL scheme (which would need to be app-specific)
- A debug view controller with some actions:
  - Zip up the documents directory and attach to an email addressed to the support email
  - Email IAP receipt (I don't have experience with this so I'm not sure if this can be handled generically)
  - Clear keychain items

**Comment by vokal-isaac** [comment]
Clearing keychain-stored items is another good thing to have on that menu (since they persist across delete-and-reinstalls of the app).

**Comment by brockboland** [comment]
Good point, adding it to the list.

**Comment by bryanluby** [comment]
Closing as there are now numerous open source pods that can be used if the need arrives for this.
