### ISSUE TITLE
Xcode 9 template changes

### ISSUE THREAD

**Issue by bill350** [vokal/Xcode-Template#36]
Hi Vokal team,

I follow your work to understand Xcode templates in our team since 3 months. Good point to had open your work 👍 

Did you test on the first Xcode9-beta version ?

Now Xcode links folders with finder by default, so it produces a lot of group duplications when using  your Vokal templates for instance.

![capture d ecran 2017-06-08 a 16 58 49](https://user-images.githubusercontent.com/2437702/26935268-ca53ebfa-4c6b-11e7-8a7f-b39913fd86ec.png)

I am currently testing and adjusting your templates to see which changes and impacts we have to do.

**Comment by bryanluby** [comment]
Thanks for pointing this out 👍 . We have not had a chance to test the template against the new Xcode 9 beta yet but we may create a separate Xcode 9 branch for this purpose.

**Comment by bryanluby** [comment]
This is now fixed
