### ISSUE TITLE
Add an App Store scheme

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#4]
Right now, fastlane is the only way to get an App Store build, since it injects `USE_PRODUCTION_SERVER=YES` at build time. This variable isn't set from Xcode anywhere, so App Store builds can't be created and uploaded from Xcode.

Let's add a Production scheme that sets this variable, and use that for the `itc` and `hockey_prod` lanes.

**Comment by bryanluby** [comment]
Leaving as-is
