### ISSUE TITLE
Travis: Upload KIF failure screenshots

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#6]
KIF can take a screen shot when a test fails. Travis can do stuff when a build fails. We should combine these capabilities to help us diagnose flaky UI tests.

The screenshots could be uploaded to S3, but not everyone on the team has access to that. If we can, I'd like to have Travis attach them to an email sent to the person who opened the PR.

**Comment by vokal-isaac** [comment]
It's been well over a year since I tried it, but I utterly failed to get KIF to actually drop the screenshot files anywhere (maybe failed to get it to take screenshots at all) when I last tried.

**Comment by brockboland** [comment]
I want to say I tried it a couple months ago and couldn't get it working either, though I don't think I spent more than 10 minutes on it. This one is a low priority as far as I'm concerned.

**Comment by bryanluby** [comment]
Closing as we no longer are using KIF
