### ISSUE TITLE
Move fastfile to a common public repo

### ISSUE THREAD

**Issue by brockboland** [vokal/Xcode-Template#9]
It's possible to import the Fastfile contents from a git repo. We should do this so we have a centralized, common Fastfile that's used across all projects, so bug fixes only need to be made once.

In order to accomplish this:
- [ ] Move the project-specific variables out of the Fastfile. `workspace_file`, `project_file`, `main_scheme`, and `coverage_files_to_ignore` all make use of the app name (as `___PACKAGENAME___`).
- [ ] Do some testing and confirm that using the git import works as expected
- [ ] Decide on a good way to version the common fastfile. We want projects to make use of an updated Fastfile when bugs are fixed, but not when there are breaking changes made to it. We'll probably tag each version (like 1.0.2) and maintain a branch for major versions (like v1) so that project maintainers can use a specific version of the latest from a major version branch, as they see fit.
- [ ] Update our [Travis setup documentation](https://engineering.vokal.io/iOS/Fastlane-Travis-CI.md.html) once the **Variables each project must update** section is removed from the Fastfile

**Comment by kevnm67** [comment]
@brockboland What do you think about moving the project-specific variables to [.env](https://github.com/bkeepers/dotenv)? (or [fastlane specific .env](https://docs.fastlane.tools/advanced/other/))

Things to consider for .env setup:
- Adding dotenv to the gemfile
- Require dotenv in fastfile ```fastlane_require 'dotenv'```

**Comment by brockboland** [comment]
@kevnm67 I'm no longer involved in this project or using fastlane, so that would be a question for other Vokal folks. @bryanluby maybe?

**Comment by bryanluby** [comment]
Closing as this is not in our plans.
